name: Fix PHP code style issues

on:
  push:
    paths:
      - "**.php"

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        # https://github.com/aglipanci/laravel-pint-action
        uses: aglipanci/laravel-pint-action@2.5

      - name: Commit changes
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
